name: check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: "actions/checkout@v2"
      - name: run lint
        run: make lint
        # Add Code Climate secret key
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0 
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CLIMATE }}
        with:
           coverageCommand: make test-coverage
           debug: true
